version: 2
jobs:
  build-ui:
    docker:
      - image: circleci/node
    working_directory: ~/go/src/github.com/nicholasjackson/fake-service
    steps:
      - checkout
      - run:
          name: install deps
          command: cd ui && yarn install
      - run:
          name: run tests
          command: cd ui && CI=true yarn test
      - run:
          name: build UI
          command: cd ui && REACT_APP_API_URI=/ PUBLIC_URL=/ui yarn build
      - persist_to_workspace:
          root: ~/go/src/github.com/nicholasjackson
          paths:
            - fake-service

  build-go:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/nicholasjackson/fake-service
    steps:
      - attach_workspace:
          at: /go/src/github.com/nicholasjackson
      - run:
          name: add packr2 dependency
          command: GO111MODULE=off go get -u github.com/gobuffalo/packr/v2/packr2
      - run: 
          name: test application
          command: go test -v ./... 
      - run:
          name: compile UI dependencies
          command: packr2
      - run: 
          name: build application (linux)
          command: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/fake-service-linux
      - run: 
          name: build application (mac)
          command: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o bin/fake-service-osx
      - persist_to_workspace:
          root: /go/src/github.com/nicholasjackson
          paths:
            - fake-service
  
  release:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/nicholasjackson/fake-service
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/nicholasjackson
      - run: 
         name: docker login
         command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: 
         name: docker build
         command: |
           docker build -t nicholasjackson/fake-service:${CIRCLE_TAG} .
           docker build -t nicholasjackson/fake-service:vm-${CIRCLE_TAG} -f Dockerfile-VM .
      - run: 
          name: docker push
          command: |
            docker push nicholasjackson/fake-service:${CIRCLE_TAG}
            docker push nicholasjackson/fake-service:vm-${CIRCLE_TAG}
 
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/go/src/github.com/nicholasjackson/fake-service
    steps:
      - attach_workspace:
          at: ~/go/src/github.com/nicholasjackson
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -replace ${CIRCLE_TAG} ./bin/

workflows:
  version: 2
  build-and-release:
    jobs:
      - build-ui:
          filters:
            tags:
              only: /.*/
      - build-go:
          requires:
            - build-ui
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - build-go
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
